const PREFIX = '/api/v1/'
export const API_TOPICS_PATH = PREFIX + 'questions/'
export const API_SIGN_IN_PATH = PREFIX + 'users/sign_in'
export const API_SIGN_UP_PATH = PREFIX + 'users/sign_up'
export const API_SIGN_OUT_PATH = PREFIX + 'users/sign_out'
export const API_PROFILE_PATH = PREFIX + 'profile'
